package com.rm.parrotmetric.ui

// Written by tools/gen_manual.py from manual/. Edit the Markdown there and
// run the script again, not this.

/** What a line of the manual is. `code` and **bold** stay in the text. */
enum class ManualKind { Heading, Para, Bullet, Step }

class ManualBlock(val kind: ManualKind, val text: String)

class ManualSection(val title: String, val summary: String, val blocks: List<ManualBlock>)

object Manual {
    val sections: List<ManualSection> = listOf(
        ManualSection("A first part", "A plate with a hole and rounded corners, from start to finish.", listOf(
            ManualBlock(ManualKind.Para, "ParrotMetric builds a part as a list of steps. You draw a flat sketch, turn it into a solid, then change the solid with more steps. Every step is kept, so you can go back and change any of them later and the rest rebuild."),
            ManualBlock(ManualKind.Para, "The manual says tap. On a computer a click is a tap, and a right-click opens a menu where a phone would use a long press."),
            ManualBlock(ManualKind.Heading, "Starting"),
            ManualBlock(ManualKind.Para, "On the start screen, tap **New design**. The model screen opens with nothing in it yet."),
            ManualBlock(ManualKind.Heading, "A sketch"),
            ManualBlock(ManualKind.Step, "Tap **Sketch**, then **Top**. The view turns to look straight down at the top plane."),
            ManualBlock(ManualKind.Step, "Tap **Rectangle**, then tap two corners. Its width and height show at the bottom."),
            ManualBlock(ManualKind.Step, "Type `60` for the width and `40` for the height, and tap **Set**."),
            ManualBlock(ManualKind.Step, "Tap **Circle**, then tap a centre inside the rectangle and a point for its size. Type `8` for the diameter and tap **Set**."),
            ManualBlock(ManualKind.Step, "Tap **Finish**."),
            ManualBlock(ManualKind.Para, "The count at the top of a sketch shows how much is still free to move. It doesn't have to be fully set, but a sketch that is stays the way you meant it when you change a size."),
            ManualBlock(ManualKind.Heading, "A solid"),
            ManualBlock(ManualKind.Step, "Tap inside the rectangle, outside the circle. The area lights up."),
            ManualBlock(ManualKind.Step, "Tap **Create**, then **Extrude**. A preview shows."),
            ManualBlock(ManualKind.Step, "Type `5` for the distance and tap **Done**."),
            ManualBlock(ManualKind.Para, "You now have a plate with a hole through it."),
            ManualBlock(ManualKind.Heading, "Rounding the corners"),
            ManualBlock(ManualKind.Step, "Tap the four short upright edges at the corners. Each one lights up as you tap it. Turn the view to reach the one at the back. With a mouse, hold Shift as you click to add each one."),
            ManualBlock(ManualKind.Step, "Tap **Modify**, then **Fillet**."),
            ManualBlock(ManualKind.Step, "Type `4` for the radius and tap **Done**."),
            ManualBlock(ManualKind.Heading, "Changing your mind"),
            ManualBlock(ManualKind.Para, "Each step is a chip along the bottom: the sketch, the extrude and the fillet. Tap the sketch's chip to open it again, tap the 60 and change it to 80, and tap **Finish**. The extrude and the fillet rebuild on the longer plate."),
            ManualBlock(ManualKind.Heading, "Saving and printing"),
            ManualBlock(ManualKind.Para, "Your design is saved as you go, and comes back next time with **Continue**. To keep it under a name, use **Save as…** in the menu under the parrot in the top corner. To print it, use **Export…** in the same menu and pick STL or 3MF."),
            ManualBlock(ManualKind.Para, "**Versions…** in that menu keeps copies of the design as it is now under a name, such as \"Before the lid\", to go back to later. They're kept in the design's file. Going back to one can be undone."),
        )),
        ManualSection("The screen", "Where things are, moving the view and picking things.", listOf(
            ManualBlock(ManualKind.Heading, "Two layouts"),
            ManualBlock(ManualKind.Para, "ParrotMetric has a layout for phones and one for large screens. It picks one by the size of the window, or you can set it in Settings. A wide but short screen, like a small tablet on its side, gets the phone layout, with the tool groups spread wider."),
            ManualBlock(ManualKind.Bullet, "On a phone, the tools are in five groups along the bottom: **Sketch**, **Create**, **Modify**, **Construct** and **Inspect**. Tap a group to see its tools. Tool settings open in a panel at the bottom."),
            ManualBlock(ManualKind.Bullet, "On a tablet, a computer or in a browser, every tool is in a toolbar along the top, the parts list is down the left and tool settings open on the right. Tools that come in a few kinds, like the planes, have a small arrow for the rest."),
            ManualBlock(ManualKind.Para, "The bar at the top has the menu under the parrot, the design's name and how many bodies it has, the parts list, and undo and redo. Tap the name to rename the design; in the projects folder its file is renamed too."),
            ManualBlock(ManualKind.Heading, "Moving the view"),
            ManualBlock(ManualKind.Bullet, "One finger turns the view."),
            ManualBlock(ManualKind.Bullet, "Two fingers move it, and pinching zooms."),
            ManualBlock(ManualKind.Bullet, "Double tap fits everything in view, and so does the button under the cube."),
            ManualBlock(ManualKind.Bullet, "The cube in the corner shows which way you're looking. Tap one of its faces to look straight at that side."),
            ManualBlock(ManualKind.Bullet, "The camera button below them keeps the view as it is under a name, **Keep this view…**, and lists the views kept, to go back to. They're saved with the design."),
            ManualBlock(ManualKind.Para, "With a mouse, the middle button moves the view, and right drag or Shift and middle drag turns it. The wheel zooms towards the pointer, and a double middle click fits everything."),
            ManualBlock(ManualKind.Heading, "Picking things"),
            ManualBlock(ManualKind.Para, "Tap a face, an edge or a corner to pick it, and tap it again to drop it. Tap empty space to clear what's picked. Hold on an edge to pick it and the edges running on smoothly from it, such as all of a rounded outline. Inside a finished sketch, tap an area to pick it, which is what Extrude and other tools use."),
            ManualBlock(ManualKind.Para, "With a mouse, a click picks just that thing and Shift or Ctrl and a click adds to what's picked. A double-click on an edge picks it and the edges running on smoothly from it, such as all of a rounded outline. Drag on empty space to pick everything in a box: dragging to the right picks what's fully inside it, and dragging to the left also picks what it touches. A right-click opens a menu with **Repeat** for the last tool, the tools that suit what's picked, **Hide**, **Isolate**, **Fit the view** and **Clear selection**."),
            ManualBlock(ManualKind.Heading, "The parts list"),
            ManualBlock(ManualKind.Para, "The layers button in the top bar opens the parts list on a phone. On a large screen it's on the left. It has every body in the design, grouped by component, and the construction planes."),
            ManualBlock(ManualKind.Bullet, "Under each body is its size along x, y and z."),
            ManualBlock(ManualKind.Bullet, "The eye shows or hides a body."),
            ManualBlock(ManualKind.Bullet, "With a tool open that works on whole bodies, such as Mirror, tap a body's name to pick it."),
            ManualBlock(ManualKind.Bullet, "The dot sets its colour, which also goes into 3MF files, and how it looks: **Plain**, **Matte**, **Glossy** or **Metal**. The look is only for the view."),
            ManualBlock(ManualKind.Bullet, "The menu beside it has **Rename…**, **Isolate**, **See-through**, and puts the body into a component or takes it out (see Components and joints). A component's menu has **Isolate** and **See-through** too. A see-through body shows what's inside it, such as a board in its case; **Solid** turns it back."),
            ManualBlock(ManualKind.Para, "**Isolate** shows only those bodies, or the bodies of the faces picked when chosen from the right-click menu, and leaves the rest out of view until you tap **Show all** on the note at the top of the view. It only changes what's shown: exports, drawings and the bill of materials still have every body that isn't hidden."),
            ManualBlock(ManualKind.Para, "Under **Planes** are the construction planes, each with an eye to hide it once you've drawn on it."),
            ManualBlock(ManualKind.Heading, "The history"),
            ManualBlock(ManualKind.Para, "The chips along the bottom are the steps that make the design, oldest on the left. The orange bar is where the history ends right now. When their names don't all fit, the chips show just their icons, over up to three rows on a large screen and in one row that scrolls on a phone; hover or long press to see a step's name."),
            ManualBlock(ManualKind.Bullet, "Tap a chip to open that step's settings again."),
            ManualBlock(ManualKind.Bullet, "A long press on a chip (or a right-click) gives **Edit**, **Roll back to here**, **Turn off** and **Delete**. A sketch's also has **Move to picked face**: pick a plane or a flat face first, and the sketch moves onto it with what's drawn in it. **Save as DXF…** saves what's drawn in the sketch, and its text, as a DXF for a laser cutter or another drawing program; construction lines are left out."),
            ManualBlock(ManualKind.Para, "**Roll back to here** moves the end of the history back to that step, so the steps after it stop for now. Anything you add then goes in at that point. **Roll forward to here** brings them back."),
            ManualBlock(ManualKind.Para, "**Turn off** keeps a step but leaves it out, to see the part without it."),
            ManualBlock(ManualKind.Para, "A step that can't be built turns red and says why, and the steps after it still try. Usually it's because an edge or face it used isn't there any more, and opening it to pick again fixes it."),
            ManualBlock(ManualKind.Heading, "Tool panels"),
            ManualBlock(ManualKind.Para, "A tool's panel has its choices along the top and its sizes below, with **Done** and **Cancel**. Most tools show a preview that updates as you change things. Fillet, Chamfer and the tools for faces show the body without the change while their panel is open, so you can keep picking edges and faces on it. If the step can't be made, the reason shows above **Done**."),
            ManualBlock(ManualKind.Para, "Any size can be a sum, like `20+5` or `wall*2`, using your parameters (see Parameters and configurations). Sizes are in millimetres and angles in degrees."),
            ManualBlock(ManualKind.Para, "On a touch screen with no keyboard, tapping a size brings up a number pad beside it. **abc** swaps it for the keyboard, for parameter names and units, and ✓ sets the size or moves on to the next one."),
            ManualBlock(ManualKind.Para, "Most tools that make or change a shape ask what to do with it:"),
            ManualBlock(ManualKind.Bullet, "**New body** keeps it as a body of its own."),
            ManualBlock(ManualKind.Bullet, "**Join** adds it to the bodies it touches."),
            ManualBlock(ManualKind.Bullet, "**Cut** takes it away from them."),
            ManualBlock(ManualKind.Bullet, "**Intersect** keeps only where they overlap."),
        )),
        ManualSection("Sketching", "Drawing shapes, and setting their sizes and how they relate.", listOf(
            ManualBlock(ManualKind.Para, "A sketch is a flat drawing on a plane. The closed areas in it are what Extrude, Revolve and the other tools turn into solids."),
            ManualBlock(ManualKind.Heading, "Starting a sketch"),
            ManualBlock(ManualKind.Bullet, "**Sketch** then **Top**, **Front** or **Right** draws on one of the three main planes."),
            ManualBlock(ManualKind.Bullet, "To draw on a flat face of a body, pick the face and tap **On selected** (the pencil). It works the same on a construction plane, and on a flat area of a mesh. Construction planes are also listed under Sketch, after Top, Front and Right."),
            ManualBlock(ManualKind.Para, "The view turns to look straight at the plane, with x running to the right. A sketch opened again from the history starts with **Select**. The fit button at the top brings the whole sketch into view, and undo and redo there work inside the sketch. **Finish** ends the sketch."),
            ManualBlock(ManualKind.Heading, "Drawing"),
            ManualBlock(ManualKind.Para, "The tools are along the bottom: **Select**, **Line**, **Rectangle**, **Circle** and **Arc**, and **More** has **Point**, **Spline**, **Polygon**, **Slot**, **Ellipse**, **Conic** and **Text**. On a large screen they're all in one row."),
            ManualBlock(ManualKind.Para, "Tap to place each point. Points snap to the ends and middles of what's already there, and lines snap to level and upright, and the matching constraints are added as you draw."),
            ManualBlock(ManualKind.Bullet, "**Line** carries on from the last point until you tap the first point again, which closes the shape, or tap **Line** again to stop. A line that ends on a point already there and comes out level or upright is held that way. Closing a shape whose sides all have lengths, the longest side across from the closing line lets its length go, so changing one side moves the sides joined to it."),
            ManualBlock(ManualKind.Bullet, "**Rectangle** is corner to corner, from the centre, or three points for one at an angle."),
            ManualBlock(ManualKind.Bullet, "**Circle** is a centre and a point on it, two points across it, or three points on it."),
            ManualBlock(ManualKind.Bullet, "**Arc** is a centre then its ends, three points along it, or tangent, which carries on smoothly from the end of a line or arc."),
            ManualBlock(ManualKind.Bullet, "**Polygon** has as many sides as you set, with its corners on the circle you draw or its sides touching it. Its size is that circle's diameter. Typed while drawing, the diameter comes first, then **Turn**, the angle its first corner points at, or its first side's middle when the sides touch the circle."),
            ManualBlock(ManualKind.Bullet, "**Slot** is centre to centre, end to end, or from the middle."),
            ManualBlock(ManualKind.Bullet, "**Spline** goes through the points you tap, or is pulled by them as control points. Tap **Spline** again to end it."),
            ManualBlock(ManualKind.Bullet, "**Ellipse** is a centre, then the end of one axis, then the width."),
            ManualBlock(ManualKind.Bullet, "**Conic** is two ends and a point the curve leans towards. Pick one and **Fullness** sets how full it is, between 0 and 1."),
            ManualBlock(ManualKind.Bullet, "**Text** asks for the words, the height, the font, whether it's bold, where the point you tapped is on it (**From the left**, **Centred** or **From the right**) and how far it's **Turned**. Its letters are areas like any other, so they extrude. **Change text**, or a double click on the text, edits it later. - The fonts are **Sans**, **Serif**, **Mono** and **Rounded**. **Font file…** uses any TrueType or OpenType font (.ttf or .otf); it's kept with the design, so the text can be changed on any device. A font file has no bold. - **Into lines** turns the text into the lines and curves of its letters, so you can change their shapes, add to them or dimension them. It stops being text."),
            ManualBlock(ManualKind.Para, "The styles of each tool show above the tools while it's in hand."),
            ManualBlock(ManualKind.Para, "As soon as a shape is placed, its sizes show at the bottom as you drew them: a rectangle's width and height, a circle's diameter, an arc's radius, a line's length, and so on. Type the sizes you want and tap **Set**, and they become dimensions. To leave it free, just carry on drawing."),
            ManualBlock(ManualKind.Para, "**Construction** makes new curves construction curves, drawn dashed. They help you place things but don't make areas. With curves picked, it switches those instead."),
            ManualBlock(ManualKind.Heading, "Dimensions"),
            ManualBlock(ManualKind.Para, "Tap **Dimension**, then tap what to measure:"),
            ManualBlock(ManualKind.Bullet, "a line for its length"),
            ManualBlock(ManualKind.Bullet, "a circle for its diameter, or an arc for its radius"),
            ManualBlock(ManualKind.Bullet, "two points, or a point and a line, for the distance between them"),
            ManualBlock(ManualKind.Bullet, "two lines for the angle between them"),
            ManualBlock(ManualKind.Para, "Type the size and tap **Set**. A size can use your parameters, like `width/2`. Tap a dimension later to change it."),
            ManualBlock(ManualKind.Heading, "Constraints"),
            ManualBlock(ManualKind.Para, "Constraints keep things in place relative to each other. Pick the things it's about and **Constrain**, in the row above the tools, lists what fits them."),
            ManualBlock(ManualKind.Para, "The constraints are:"),
            ManualBlock(ManualKind.Bullet, "**Coincident**, **Horizontal**, **Vertical**, **Parallel**, **Perpendicular**, **Tangent** and **Equal**"),
            ManualBlock(ManualKind.Bullet, "**Fix**, which holds a point where it is"),
            ManualBlock(ManualKind.Bullet, "**Midpoint**, **Symmetric**, **Concentric** and **Collinear**"),
            ManualBlock(ManualKind.Para, "The count at the top shows how much in the sketch can still move. When it says **Fully set**, everything is held by a dimension or a constraint, and the curves change colour to show it."),
            ManualBlock(ManualKind.Para, "Constraints show as small marks beside what they hold. Tap one to pick it, and **Delete** takes it off. If a new one can't fit with the rest, the sketch says so and leaves it out."),
            ManualBlock(ManualKind.Heading, "Changing what's drawn"),
            ManualBlock(ManualKind.Para, "With **Select** in hand, drag points or curves to move them. Tap a curve twice quickly to pick the whole outline it's part of. The row above the tools has these, some only once the right things are picked. Where there's room they're each a button, with their names on a wide screen; on a narrow one they're grouped under **Change**, **Copy and move** and **Bring in**, which open above the row. Hover over an icon, or press and hold it, to see its name."),
            ManualBlock(ManualKind.Bullet, "**Trim** takes away the piece of a curve you tap, up to where it crosses other curves."),
            ManualBlock(ManualKind.Bullet, "**Extend** stretches the line end you tap to the next curve it would meet."),
            ManualBlock(ManualKind.Bullet, "**Break** cuts a curve in two where you tap."),
            ManualBlock(ManualKind.Bullet, "**Offset** makes a copy of the picked curves a set distance away. The copy keeps that distance as a size, typed as a parameter if you like, such as `gap+wall`, so changing the parameter moves the copy. A distance below 0 goes inwards, such as `-wall`. Round an outline with rounded corners, one size holds all of it."),
            ManualBlock(ManualKind.Bullet, "**Round corner** and **Cut corner** round off or cut corners: pick the corner points, or the lines that meet there, or tap an outline twice to do all its corners. Sizes measured to a corner still measure to where the lines would meet."),
            ManualBlock(ManualKind.Bullet, "**Mirror** copies the picked curves across a line. Pick the line last. They stay mirrored when you change them."),
            ManualBlock(ManualKind.Bullet, "**Move** and **Scale** move or resize the picked curves."),
            ManualBlock(ManualKind.Bullet, "**Pattern** copies them in a row, **X apart** and **Y apart**, and with **Rows** more than 1, repeats the row **Rows apart**, square to it. **Stagger the rows** puts every other row half a step along, for a honeycomb. The copies stay tied to what was copied: move it and they follow, and the first step across and up are sizes you can change to respace them all. With circles picked, **Grow by** makes each circle that much bigger across than the one before, for a tolerance test. **Pattern round** copies them round a point."),
            ManualBlock(ManualKind.Bullet, "**Delete** takes away what's picked."),
            ManualBlock(ManualKind.Heading, "Bringing things in"),
            ManualBlock(ManualKind.Bullet, "**Project** brings a face's edges into a sketch drawn on that face, or where the bodies cross the sketch's plane, as fixed curves to draw against. They stay tied to what they came from: change the part they came from, such as a board you're making a case for, and they move with it, along with anything sized from them. If its edges change shape, say a hole is added, the sketch says so and you project again."),
            ManualBlock(ManualKind.Bullet, "**Add drawing** brings in an SVG or DXF file's curves, at their size in the file in millimetres."),
            ManualBlock(ManualKind.Bullet, "A picture to trace over goes in with **Canvas**, under **Construct**."),
        )),
        ManualSection("Making solids", "Extrude, revolve, sweep, loft, pipe, coil and the ready-made shapes.", listOf(
            ManualBlock(ManualKind.Para, "These are under **Create**. Most start from sketch areas: pick the areas, then the tool. You can also start the tool and tap areas while its panel is open."),
            ManualBlock(ManualKind.Heading, "Extrude"),
            ManualBlock(ManualKind.Para, "Pushes areas straight out of their plane. Tap the areas first, or with none tapped it takes the newest sketch when it has only one. When that sketch has more, **Take all** takes every one of its areas."),
            ManualBlock(ManualKind.Para, "A flat face of a body extrudes too, with no sketch: tap it, then Extrude. It goes out from the face and joins the body, holes and all, or with **Cut** it sinks into the body."),
            ManualBlock(ManualKind.Bullet, "**Distance** goes a set distance, **Through all** goes through everything in the way, and **Up to** stops at a face or plane you pick."),
            ManualBlock(ManualKind.Bullet, "With a distance, it goes **One side**, **Both ways** (the same each way) or **Two sides** (a different distance each way). **The other way** turns a one-sided extrude round, the same as a distance below 0. With the other two, pick **Forward**, **Back** or **Both ways**."),
            ManualBlock(ManualKind.Bullet, "**Through all** starts as **Cut**, since it goes through bodies."),
            ManualBlock(ManualKind.Bullet, "**Taper** leans the sides in or out by an angle."),
            ManualBlock(ManualKind.Bullet, "**Start at** starts it a distance away from the sketch's plane."),
            ManualBlock(ManualKind.Bullet, "**Thin wall** makes a wall of a set thickness round the outline instead of a solid. A sketch of just an open line, like the shape of a clip, extrudes as a wall that thick along the line, with round ends."),
            ManualBlock(ManualKind.Heading, "Revolve"),
            ManualBlock(ManualKind.Para, "Turns areas round an axis: the sketch's **Y axis** or **X axis**, or a line in the sketch. **Angle** is how far it goes, 360 for all the way round. **As a surface**, here and in Extrude, makes the sketch's lines a surface instead (see Surfaces)."),
            ManualBlock(ManualKind.Heading, "Sweep"),
            ManualBlock(ManualKind.Para, "Moves areas along a path: a sketch's curves, or edges you pick. Pick the areas, start **Sweep**, then choose the path under **Along**."),
            ManualBlock(ManualKind.Heading, "Loft"),
            ManualBlock(ManualKind.Para, "Joins areas in different sketches into one shape, in the order you pick them. Each sketch is usually on a plane above the last. **Straight between them** joins them with flat sides instead of a smooth curve through all of them."),
            ManualBlock(ManualKind.Bullet, "**Twist** turns the areas round, the last by the angle given and those between in step, for twisted vases and columns."),
            ManualBlock(ManualKind.Bullet, "**Follow a guide** makes the sides run along a line from a sketch, or edges picked in the view. The line should start on the first area and end on the last."),
            ManualBlock(ManualKind.Heading, "Pipe"),
            ManualBlock(ManualKind.Para, "A round pipe along a path, with its **Diameter**. **Hollow** makes it a tube with the inside diameter you give."),
            ManualBlock(ManualKind.Heading, "Coil"),
            ManualBlock(ManualKind.Para, "A spring or a spiral, with no sketch needed. Set the plane it stands on, the **Diameter**, the **Pitch** (the rise for each turn), the number of **Turns**, and the **Wire** size, round or square."),
            ManualBlock(ManualKind.Heading, "Shapes"),
            ManualBlock(ManualKind.Para, "**Box**, **Cylinder**, **Sphere**, **Torus** and **Cone** make a shape from sizes, without a sketch. Pick the plane it sits on, its sizes and where its centre is. It sits on the side the plane faces, and **Grow the other way** puts it on the other side."),
            ManualBlock(ManualKind.Heading, "Gear"),
            ManualBlock(ManualKind.Para, "A gear, under **Shapes**, with no sketch needed. Set the plane it stands on and:"),
            ManualBlock(ManualKind.Bullet, "**Module**, the size of the teeth: the pitch circle, where it meets another gear, is the module times the teeth across. Gears that mesh have the same module."),
            ManualBlock(ManualKind.Bullet, "**Teeth** and **Thickness**."),
            ManualBlock(ManualKind.Bullet, "**Straight**, **Helical** or **Herringbone** teeth, with the **Helix angle** for the last two. Herringbone teeth go one way then back, so the gears don't push each other sideways."),
            ManualBlock(ManualKind.Bullet, "**Pressure angle**, 20° unless you're matching a gear made otherwise."),
            ManualBlock(ManualKind.Bullet, "**Bore**, a hole through the middle for the shaft, 0 for none."),
            ManualBlock(ManualKind.Bullet, "**Clearance** takes a little off each tooth so printed gears don't bind. 0.1 to 0.2 mm suits most printers."),
            ManualBlock(ManualKind.Para, "**Beside** puts it next to a gear made before it, turned so their teeth mesh, with the same module and the helix the other way. **Round from it** sets where round that gear it goes. It follows that gear when you change it. The panel shows how far apart their centres are."),
            ManualBlock(ManualKind.Heading, "New body, join, cut or intersect"),
            ManualBlock(ManualKind.Para, "Each of these asks what to do with the shape (from a sketch on a body's face it starts as Join): keep it as a **New body**, **Join** it to the bodies it touches, **Cut** it out of them, or **Intersect** to keep only where they overlap. A cut extrude is how you make most holes and pockets. Under **Changes** you can pick which bodies it changes, so a port cut through the case wall leaves the board's socket alone. **Any it reaches** is the default."),
        )),
        ManualSection("Changing solids", "Rounding, hollowing, holes, patterns and the other Modify tools.", listOf(
            ManualBlock(ManualKind.Para, "These are under **Modify**. Pick what the tool works on first, or start it and pick while its panel is open."),
            ManualBlock(ManualKind.Heading, "Edges"),
            ManualBlock(ManualKind.Bullet, "**Fillet** rounds edges. **Radius** is the same all along, **Start to end** goes from one radius to another along the edge, and **Across** sets the width of the round instead of its radius."),
            ManualBlock(ManualKind.Bullet, "**Chamfer** cuts edges off at an angle. **Equal** is the same distance on both faces, **Two distances** a different one on each, and **With angle** a distance and an angle. **Swap sides** swaps which face gets which."),
            ManualBlock(ManualKind.Para, "Edges that join smoothly are taken together, so one tap can pick the whole way round a rounded corner."),
            ManualBlock(ManualKind.Heading, "Faces"),
            ManualBlock(ManualKind.Bullet, "**Shell** hollows the body out to the wall thickness you give. The faces you pick are left open, and with none it's hollow inside."),
            ManualBlock(ManualKind.Bullet, "**Lip** stands a lip round the inside of an opening, on the top of its wall: tap the top face, then set the **Width** and **Height**. Under **Groove in**, pick the lid and it gets a groove the lip fits into, with the **Gap** you give all round (0.2 mm to start). The lid should sit on the top of the wall."),
            ManualBlock(ManualKind.Bullet, "**Snap fit** puts a clip at each point in a sketch on a face, such as points along the inside of the walls on a lid's underside. Each is a beam standing out of the face with a hook at its end, pointing away from the middle of the part, so it catches the wall. Set its **Length**, **Width** and **Thickness**, how far the hook sticks out (**Overhang**) and how long it is (**Hook**). Under **Catch in**, pick the other part and it gets a recess for each hook, with the **Gap** you give."),
            ManualBlock(ManualKind.Bullet, "**Press pull** moves a face in or out, and the faces next to it follow. A distance above 0 adds to the body, which makes a hole smaller. The panel says which way it goes."),
            ManualBlock(ManualKind.Bullet, "**Delete face** takes faces away and closes the gap, for getting rid of a round or a small feature."),
            ManualBlock(ManualKind.Bullet, "**Draft** tilts faces by an angle, for parts that need to come out of a mould. Pick the faces to tilt, then switch to **Pivot face** and pick the face they turn about."),
            ManualBlock(ManualKind.Heading, "Holes and threads"),
            ManualBlock(ManualKind.Bullet, "**Hole** puts a hole at each point in a sketch on a face, and at the corners and centres of its construction lines and circles, the origin too when a construction circle is round it. It's **Simple**, **Counterbore** (a wider, flat bottomed hole at the top for a bolt head) or **Countersink** (a cone at the top for a flat head screw). Set the **Diameter**, and the **Depth** or **All the way through**. For a screw in a printed part, pick **Insert** for a pocket that takes a heat-set insert, **Self-tap** for a hole the screw cuts its own thread in, or **Clearance** for a hole it passes through, then the screw size, M2 to M5. Insert also sets the depth to fit a standard insert, and Clearance with Countersink or Counterbore makes room for the screw's head. Typing a diameter goes back to **Any size**. **Changes** picks which bodies it cuts into. A new hole starts the same as the last one made."),
            ManualBlock(ManualKind.Bullet, "**Thread** cuts a modelled thread into a round face, a hole or a shaft, with the **Pitch** you give, or the pitch of the size picked: **Metric**, M2 to M64, or **Inch**, UNC #2-56 to 1-8. **Clearance** makes a shaft smaller or a hole bigger by that much first, so printed threads screw together (0.2 to 0.4 mm on each part). Make a hole for a thread at the nut size first: the panel shows it for a shaft, and for a hole the bolt it takes. A hole's thread sits half a turn round from a shaft's, so a lid and its jar mesh where they stand. **Only draw it** leaves the face as it is and draws the thread on it as a fine spiral, for parts that aren't printed with their threads, and it's much quicker."),
            ManualBlock(ManualKind.Bullet, "**Fastener** puts a standard **Socket cap**, **Hex bolt** or **Countersunk** screw, a **Nut** or a **Washer** in a hole: tap the hole's round side, or a countersink's cone so the head sits flush. It picks the biggest size that goes through and makes a screw as long as the hole is deep. It sits at the hole's top end, or with **From the other end** at the bottom, where a nut goes. With no hole tapped it stands on a plane where you set it. Sizes are **Metric**, M2 to M12, or **Inch**, #4-40 to 1/2-13. Its thread is only drawn unless you turn on **Model the thread**. With **Cut** and a little **Clearance** it cuts a pocket it fits in, such as a nut trap."),
            ManualBlock(ManualKind.Heading, "Ribs and emboss"),
            ManualBlock(ManualKind.Bullet, "**Rib** grows a wall from an open line in a sketch until it meets the body, like a support inside a box. **Web** is the same but lies flat in the sketch's plane. Set the **Thickness**. It grows towards the body by itself; when both sides reach the body, **Grow the other way** picks the other one."),
            ManualBlock(ManualKind.Bullet, "**Emboss** raises or sinks sketch areas into a face, flat or curved. Pick the areas and the face, choose **Raised** or **Sunk** and the depth. Text on a round part follows the curve. With no areas picked it uses all of the newest sketch, leaving the middles of letters open, which suits text drawn through the middle of a part where you can't tap it."),
            ManualBlock(ManualKind.Heading, "Mirror and pattern"),
            ManualBlock(ManualKind.Bullet, "**Mirror** copies across a plane or a flat face."),
            ManualBlock(ManualKind.Bullet, "**Pattern** makes copies **In a row** (and a second row for a grid, with **Stagger the rows** for every other row half a step along), **Round an axis**, or **Along a path**."),
            ManualBlock(ManualKind.Para, "Both work on **Bodies**, or on **Features**: the steps that made something, like a hole and its fillet, which are done again at each copy. A mirror or pattern of features can itself be picked, so a groove mirrored the other way round can be patterned round a knob for a diamond knurl. Copies of bodies can be joined to the original with **Join to the original**."),
            ManualBlock(ManualKind.Para, "Along a path, the copies are spread evenly along it or **Spaced** a set distance apart. **Turn with the path** turns each one to follow the path, and **Start from the other end** starts from the path's other end."),
            ManualBlock(ManualKind.Heading, "Bodies"),
            ManualBlock(ManualKind.Para, "Tools that work on whole bodies also list them by name in their panel, to pick one that's hidden or hard to tap."),
            ManualBlock(ManualKind.Bullet, "**Combine** joins, cuts or intersects bodies with each other. Tap the body to keep first, then each body to use on it (with a mouse, Shift-click those). **Keep the others** keeps the bodies used as tools."),
            ManualBlock(ManualKind.Bullet, "**Split** cuts a body in two **By a plane** or **By a body**, keeping both pieces as bodies or only the side you want. It also trims surfaces."),
            ManualBlock(ManualKind.Bullet, "**Move** moves and turns bodies by set distances and an angle. **Move a copy** leaves the original where it was."),
            ManualBlock(ManualKind.Bullet, "**Scale** makes bodies bigger or smaller, the same every way or by a different amount along each axis."),
            ManualBlock(ManualKind.Bullet, "**Align** moves a body so the face you picked meets another face or plane, with a **Gap**, and can **Line up the middles** and make them **Face the same way**."),
        )),
        ManualSection("Construction", "Planes, axes and points to build on, and pictures to trace.", listOf(
            ManualBlock(ManualKind.Para, "These are under **Construct**. They don't make anything you print, but they give you places to sketch and things to measure from. They show in the view and can be picked like faces and edges."),
            ManualBlock(ManualKind.Heading, "Planes"),
            ManualBlock(ManualKind.Bullet, "**Offset plane** is parallel to a plane or flat face, a distance away."),
            ManualBlock(ManualKind.Bullet, "**Angled plane** is turned about one of its axes by an angle."),
            ManualBlock(ManualKind.Bullet, "**Midplane** is halfway between two planes or faces."),
            ManualBlock(ManualKind.Bullet, "**Plane through three points** goes through three corners or points you pick."),
            ManualBlock(ManualKind.Bullet, "**Plane through two edges** goes through two straight edges."),
            ManualBlock(ManualKind.Bullet, "**Tangent plane** touches a round face."),
            ManualBlock(ManualKind.Bullet, "**Plane along an edge** is square to an edge at a point along it, as a percentage of the way along, for sketching a sweep's shape."),
            ManualBlock(ManualKind.Heading, "Axes"),
            ManualBlock(ManualKind.Para, "**Axis** is along a line through a point you give, along a straight edge, through the middle of a round face, or between two points. Revolve and Pattern can use it."),
            ManualBlock(ManualKind.Heading, "Points"),
            ManualBlock(ManualKind.Para, "**Point** is at a place you type, at a corner or the centre of a round edge, or where three planes meet. Project brings points into a sketch."),
            ManualBlock(ManualKind.Heading, "Canvas"),
            ManualBlock(ManualKind.Para, "**Canvas** lays a picture on a plane to trace over in a sketch. Set its **Width**, where its centre is and how far it's **Turned**. It isn't part of the model and doesn't export."),
        )),
        ManualSection("Meshes", "STL, 3MF and OBJ files, and what you can do with them.", listOf(
            ManualBlock(ManualKind.Para, "A mesh is a shape made of triangles, like most files for 3D printing. ParrotMetric keeps one as a mesh body, which works with most of the tools for solids."),
            ManualBlock(ManualKind.Heading, "Bringing one in"),
            ManualBlock(ManualKind.Para, "**Import** under **Create**, or **Open…** in the menu, with an STL, 3MF or OBJ file adds it to the design you're in as a mesh body. From the start screen it starts a new design. It's a step in the history like any other."),
            ManualBlock(ManualKind.Para, "On the way in it's repaired: points that should be shared are joined, faces are turned the right way out and small holes are closed. If it still isn't closed up, it says so, since some tools need a closed mesh."),
            ManualBlock(ManualKind.Heading, "Tools for meshes"),
            ManualBlock(ManualKind.Para, "With a mesh picked, **Modify** shows the tools that work on it:"),
            ManualBlock(ManualKind.Bullet, "**Plane cut** cuts it with a plane and keeps one side or both."),
            ManualBlock(ManualKind.Bullet, "**Reduce** uses fewer triangles, within the **Allowed error** you give."),
            ManualBlock(ManualKind.Bullet, "**Remesh** makes the triangles even, none longer than the **Longest edge**."),
            ManualBlock(ManualKind.Bullet, "**Smooth** rounds it off over a number of **Steps**, keeping edges sharper than the angle in **Sharp over**."),
            ManualBlock(ManualKind.Bullet, "**Hollow** leaves walls the **Wall** thickness all round inside, for a lighter print or less resin. The inside follows the outside, a little rougher. On a large part with thin walls it says to make them thicker."),
            ManualBlock(ManualKind.Bullet, "**Erase and fill** takes away the surface where you tap and fills each hole it leaves with a smooth patch that carries on the curve round it, to get rid of a bump, a seam or a bit of a scan you don't want. **Size** is how big the next spot is, and **Take back the last** takes the last spot back."),
            ManualBlock(ManualKind.Bullet, "**Separate** makes each piece that isn't joined to the rest a body of its own, the biggest keeping the name. It works on solids too."),
            ManualBlock(ManualKind.Bullet, "**To solid** turns a small mesh into a solid (the only one shown, if none is picked), joining flat triangles into faces, so Fillet and the other solid tools work on it. A big mesh gets slow, so reduce it first."),
            ManualBlock(ManualKind.Bullet, "**Hole**, **Mirror**, **Pattern**, **Combine**, **Split**, **Move**, **Scale**, **Align** and **Joint** work as they do for solids."),
            ManualBlock(ManualKind.Para, "The panel shows how many triangles there are."),
            ManualBlock(ManualKind.Heading, "Meshes and solids together"),
            ManualBlock(ManualKind.Para, "Combine and the join, cut and intersect choices work between a mesh and a solid. The result is a mesh."),
            ManualBlock(ManualKind.Para, "To sketch on a mesh, pick a flat area of it and tap **On selected**. Then extrude, cut and so on as usual."),
        )),
        ManualSection("Sculpting", "Pushing, pulling and smoothing a shape like clay, with brushes.", listOf(
            ManualBlock(ManualKind.Para, "Sculpting works on a mesh the way you'd work clay: push it in, pull it out, smooth it, pinch a crease. It suits figures, faces, creatures and anything organic that's hard to draw with sketches."),
            ManualBlock(ManualKind.Heading, "Starting"),
            ManualBlock(ManualKind.Para, "**Sculpt** is under **Create**, or press K:"),
            ManualBlock(ManualKind.Bullet, "With a face of a body picked, it sculpts that body. A solid is turned into even triangles first."),
            ManualBlock(ManualKind.Bullet, "With nothing picked, it starts from a ball 50 mm across. **Sculpt a ball** and **Sculpt a block** start from those whatever is picked."),
            ManualBlock(ManualKind.Para, "**Done** puts what you've sculpted into the history as a Sculpt step, as a mesh body, with its mask. Tap the step later to sculpt it more. The cross at the top left leaves without keeping it."),
            ManualBlock(ManualKind.Para, "A Sculpt step remembers its strokes. If you change a step before it, say the size of the box it was sculpted from, the strokes are made again on the changed body, where they fall on the screen as you made them. That takes a moment for a lot of strokes. While the body it came from is unchanged, the step just keeps its finished mesh."),
            ManualBlock(ManualKind.Heading, "Strokes"),
            ManualBlock(ManualKind.Para, "On the model, a finger, a pen or the left mouse button makes a stroke. Off the model, it turns the view. Two fingers move the view and pinch to zoom; with a mouse, the right button turns it, the middle one moves it and the wheel zooms."),
            ManualBlock(ManualKind.Bullet, "Hold Shift to smooth with any brush, and Ctrl to do the opposite of the brush. A pen's eraser end does the opposite too."),
            ManualBlock(ManualKind.Bullet, "**Size** is the brush's size on the screen, so zooming in works finer. **[** and **]** change it."),
            ManualBlock(ManualKind.Bullet, "**Strength** is how much each stroke does. Each brush keeps its own."),
            ManualBlock(ManualKind.Bullet, "**Invert** does the opposite: Draw pushes in, Clay digs, Mask rubs off."),
            ManualBlock(ManualKind.Bullet, "**Mirror** **X**, **Y** and **Z** repeat each stroke across the planes through the middle of what you're sculpting, as it was when you started. A ball or block starts at the origin. Seen from the front, X makes the left and right sides the same."),
            ManualBlock(ManualKind.Heading, "The brushes"),
            ManualBlock(ManualKind.Bullet, "**Draw** pushes the surface out, or in with Invert."),
            ManualBlock(ManualKind.Bullet, "**Clay** builds up flat layers, like adding clay."),
            ManualBlock(ManualKind.Bullet, "**Crease** cuts a sharp groove and pinches its sides together; inverted, a sharp ridge."),
            ManualBlock(ManualKind.Bullet, "**Smooth** evens out bumps."),
            ManualBlock(ManualKind.Bullet, "**Flatten** presses it towards a flat plane."),
            ManualBlock(ManualKind.Bullet, "**Inflate** swells it out all round, like blowing it up."),
            ManualBlock(ManualKind.Bullet, "**Pinch** pulls it in towards the brush's middle, sharpening edges."),
            ManualBlock(ManualKind.Bullet, "**Grab** drags what was under the brush when the stroke began."),
            ManualBlock(ManualKind.Bullet, "**Pull** drags the surface along with the brush, stretching it into horns, limbs and tails. With **Detail** on it keeps adding triangles as it goes."),
            ManualBlock(ManualKind.Bullet, "**Layer** raises it to a set height and no further in one stroke, for even plates and scales."),
            ManualBlock(ManualKind.Bullet, "**Mask** paints a mask, shown blue-grey, that the other brushes leave alone. **More** has **Clear** and **Invert** for it."),
            ManualBlock(ManualKind.Heading, "Detail"),
            ManualBlock(ManualKind.Para, "With **Detail** on, triangles are added under the brush where it needs them, so the surface stays smooth wherever you work. How fine is under **More**, from **Coarse** to **Fine**, and it goes with the brush's size: a small brush adds finer detail."),
            ManualBlock(ManualKind.Para, "**More** also has, for the whole mesh: **Finer all over**, which about doubles the triangles, **Coarser**, which about halves them, and **Even**, which evens them out at the size they are. The count is under the title."),
            ManualBlock(ManualKind.Para, "How many triangles it can take depends on the device: about half a million on a slow tablet, more on a fast one."),
            ManualBlock(ManualKind.Heading, "More"),
            ManualBlock(ManualKind.Bullet, "**Look**, under **More**, shows it as clay, stone, porcelain or terracotta, whichever shows the shape best to you."),
            ManualBlock(ManualKind.Bullet, "**Show the triangles** draws them over it (Shift+W), to see how fine it is where."),
            ManualBlock(ManualKind.Bullet, "**Steady lines** makes the brush trail behind the pointer on a string, so strokes come out smooth. Good for long lines with a finger or a mouse."),
            ManualBlock(ManualKind.Bullet, "**Pen pressure** can change the strength, the size or both."),
            ManualBlock(ManualKind.Bullet, "Undo and redo go back a stroke at a time."),
            ManualBlock(ManualKind.Para, "What's being sculpted is kept if the app goes into the background or closes, as if you'd pressed Done."),
            ManualBlock(ManualKind.Para, "A sculpted body is a mesh, so the mesh tools work on it afterwards, and it exports to STL or 3MF for printing like any other."),
        )),
        ManualSection("Surfaces", "Thin sheets with no thickness, and making solids from them.", listOf(
            ManualBlock(ManualKind.Para, "A surface is a face on its own, not closed into a solid. They're useful for shapes that are easier to make face by face. These tools are under **Create**."),
            ManualBlock(ManualKind.Bullet, "**Extrude** and **Revolve** with **As a surface** push or turn a sketch's lines into a surface, instead of filling areas. A revolve of just open lines is always a surface."),
            ManualBlock(ManualKind.Bullet, "**Offset surface** copies the faces you tap and moves the copy out by the **Distance**, or in when it's below 0, as a new surface. It's handy for a skin over a curved part."),
            ManualBlock(ManualKind.Bullet, "**Patch** makes a surface from **Sketch areas**, or with **Fill edges** fills a gap inside a loop of edges you pick, with a smooth face that meets them."),
            ManualBlock(ManualKind.Bullet, "**Stitch** joins surfaces you tap into one. If they close up all the way round, it makes a solid."),
            ManualBlock(ManualKind.Bullet, "**Thicken** gives a surface a thickness to make it a solid, to one side or **Both sides**."),
            ManualBlock(ManualKind.Para, "**Split** trims a surface with a plane or a body, the same as it splits a solid."),
        )),
        ManualSection("Components and joints", "Grouping bodies into parts, designs made of other designs, and parts that move.", listOf(
            ManualBlock(ManualKind.Heading, "Components"),
            ManualBlock(ManualKind.Para, "A component is a group of bodies that belong together, like the lid of a box. In the parts list, the menu beside a body has **Into a new component…** and **Into** each component there is already, and **Out of** to take it out again. The parts list shows bodies under their component, and Export can pick a whole component."),
            ManualBlock(ManualKind.Para, "The eye beside a component's name shows or hides all its bodies at once. Its menu has **Put new bodies here**: until you turn it off again, every body a step makes goes into that component. It lasts until you close the design. To start one before it has any bodies, tap **New component…** under the list and name it: new bodies go into it from then on."),
            ManualBlock(ManualKind.Heading, "Designs made of other designs"),
            ManualBlock(ManualKind.Para, "**Insert a design**, under **Create** with **Import**, builds another of your designs into this one as a component, named after its file. It lists the designs in your projects folder, and **From a file…** takes one from anywhere. You can insert the same one more than once."),
            ManualBlock(ManualKind.Para, "A design keeps a copy of each one it has in it, so it still opens anywhere. When you open it from the projects folder, the copies are brought up to date from their files, and **Update inserted ones** does it while it's open. Change the box's own design and every design with that box in it follows."),
            ManualBlock(ManualKind.Para, "Only the bodies shown in the inserted design come in. Its step's **Move x**, **Move y** and **Move z** move it; to put it in place against another part, use a joint."),
            ManualBlock(ManualKind.Heading, "Bill of materials"),
            ManualBlock(ManualKind.Para, "**Bill of materials**, under **Inspect**, lists the parts: each component, each body not in one, and the screws, nuts and washers made with Fastener, with how many there are, their size and volume. Copies of the same inserted design count as one line. **Copy the list** copies it as text for a spreadsheet."),
            ManualBlock(ManualKind.Para, "**Explode** below it draws the components apart, out from the middle of them all, to see how they go together. It only changes the view."),
            ManualBlock(ManualKind.Heading, "Joints"),
            ManualBlock(ManualKind.Para, "A joint says how one component sits on another and how it can move."),
            ManualBlock(ManualKind.Step, "Start **Joint** under **Modify**."),
            ManualBlock(ManualKind.Step, "Under **Moving**, pick the component that moves, and under **Joined to** the one it's held to, or **In place** to hold it where it is."),
            ManualBlock(ManualKind.Step, "Pick the kind: **Rigid** holds it fixed, **Turn** turns about an axis, **Slide** slides along one, **Both** does both, **Planar** slides across a flat face and turns on it, and **Ball** turns any way about a point."),
            ManualBlock(ManualKind.Step, "For turning and sliding, pick an edge or round face for the axis, or **Use an axis** for an axis you made. For **Planar**, pick the flat face it slides on. For **Ball**, pick a ball, a round edge or a flat face for its centre; with nothing picked it turns about the origin."),
            ManualBlock(ManualKind.Step, "The slider and the number at the top move it. **Planar** has two slides, and **Ball** a turn round x, y and z. Tap **Done**."),
            ManualBlock(ManualKind.Para, "To move it again later, open the joint's step and use the slider. Rigid joints keep components together when you move the one they're held to."),
            ManualBlock(ManualKind.Para, "For a pin in a slot, use **Planar** on the face the slot is in, with a slide limit to the slot's length and the other slide left at 0."),
            ManualBlock(ManualKind.Para, "### Limits"),
            ManualBlock(ManualKind.Para, "Turn on **Turn limits** or **Slide limits** and give the lowest and highest it can go. The slider then stops there, and a number past them is held at the limit."),
            ManualBlock(ManualKind.Para, "### Gears"),
            ManualBlock(ManualKind.Para, "A **Turn** joint can be geared to an earlier Turn joint: under **Geared to**, pick the one it follows. Turning that one then turns this one too. With **Ratio from the teeth** on, and both components holding a gear made with **Gear**, it turns by the teeth of the other gear over the teeth of its own, the other way round, as meshed gears do. Turn it off to give your own **Ratio**; a negative ratio turns it the other way. The joint's own turn is added on, which helps line the teeth up."),
        )),
        ManualSection("Checking a part", "Measuring, sections, and checks for printing.", listOf(
            ManualBlock(ManualKind.Para, "These are under **Inspect**."),
            ManualBlock(ManualKind.Heading, "Measure"),
            ManualBlock(ManualKind.Para, "Tap faces and edges to see their sizes, and the distance and angle between two of them. It also shows the body they're on: its volume and overall size, its area, its centre of mass, and its weight if it were solid in the material you choose: PLA, PETG, ABS, ASA, TPU, nylon, resin, aluminium, steel or brass. A print with less infill weighs less."),
            ManualBlock(ManualKind.Heading, "Section"),
            ManualBlock(ManualKind.Para, "Cuts the view through on a plane, to see inside. Pick the plane and slide it through the part. **Keep the other side** shows the other half. It only changes the view, not the part."),
            ManualBlock(ManualKind.Heading, "Print check"),
            ManualBlock(ManualKind.Bullet, "**Overhangs** colours the faces that lean out further than **Steepest**, which need support when printed."),
            ManualBlock(ManualKind.Bullet, "**Thin walls** colours the parts of walls thinner than **Thinnest**, which may not print."),
            ManualBlock(ManualKind.Heading, "Surface check"),
            ManualBlock(ManualKind.Bullet, "**Zebra** lays stripes over the part, as many as **Stripes**. Where two faces meet smoothly the stripes run on without a break."),
            ManualBlock(ManualKind.Bullet, "**Curvature** colours how tightly each part of a face curves, against the **Radius** you set."),
            ManualBlock(ManualKind.Bullet, "**Draft** shows whether a part comes out of a mould, pulled out square to **Top**, **Front**, **Right** or a **Picked face**, or **The other way**. Faces sloping out by at least the **Least draft** show green, or blue on the side it's pulled away from. Red faces slope less than that and would drag. Grey faces lie across the pull and come straight off."),
            ManualBlock(ManualKind.Heading, "Interference"),
            ManualBlock(ManualKind.Para, "Lists the bodies that overlap each other and how much, which on parts meant to fit together usually means something's wrong."),
        )),
        ManualSection("Drawings", "A sheet of views with sizes and notes, to print or send as PDF, DXF or SVG.", listOf(
            ManualBlock(ManualKind.Para, "A drawing shows the part flat, from the front, the top and the side, with its sizes written on. Each design has one. Open it with **Drawing** under **Inspect**, or Shift+W."),
            ManualBlock(ManualKind.Para, "The first time, it lays out the front, top and right views with an isometric one in the corner, at the largest standard scale they fit on the sheet. The views follow the part: change the model and they're worked out again when you come back."),
            ManualBlock(ManualKind.Heading, "Views"),
            ManualBlock(ManualKind.Bullet, "Drag a view to move it. Views line up with each other when they come close, so the side views stay in line with the front one."),
            ManualBlock(ManualKind.Bullet, "Tap a view to pick it, then turn its hidden lines on or off, or delete it. Hidden lines are dashed; the isometric view starts without them."),
            ManualBlock(ManualKind.Bullet, "**Views** adds another view: the back, left or bottom, or one taken away."),
            ManualBlock(ManualKind.Bullet, "**Section**, with a view picked, adds a section of it: the part cut through its middle, looking the same way, with the cut faces hatched. It's lettered A, B and so on, and the line it's cut along shows on the views that see it edge on, with arrows the way it looks. **Cut at** moves where it's cut, in mm along the way the view looks."),
            ManualBlock(ManualKind.Bullet, "Only solid bodies are drawn, not meshes. Bodies hidden in the parts list are left out."),
            ManualBlock(ManualKind.Bullet, "Threads, knurls and other twisting shapes are worked out from their triangles, which is much quicker, so their curves come out as short lines."),
            ManualBlock(ManualKind.Heading, "Dimensions"),
            ManualBlock(ManualKind.Para, "With **Dimension**:"),
            ManualBlock(ManualKind.Bullet, "Tap two corners, ends or centres in a view to show the distance between them. The points they catch on show as dots. It goes across or up depending on how the points lie; after making it, **Across**, **Up** and **Along** change which."),
            ManualBlock(ManualKind.Bullet, "Tap the edge of a circle for its diameter, or of an arc for its radius. **Diameter** and **Radius** switch between them."),
            ManualBlock(ManualKind.Bullet, "A hole made with Hole or threaded with Thread gets a callout instead: how many there are, its size and whether it goes through or how deep, its counterbore or countersink, or its thread, such as M4×0.7. **Hole** turns a diameter into a callout and back."),
            ManualBlock(ManualKind.Bullet, "Drag a dimension to move it further from the part, or round the circle."),
            ManualBlock(ManualKind.Para, "The numbers are the part's real sizes in mm, whatever the scale. A dimension across the part keeps to its outline, so if the part grows the dimension does too."),
            ManualBlock(ManualKind.Heading, "Notes"),
            ManualBlock(ManualKind.Para, "With **Note**, tap where it goes and type it; more than one line is fine. Drag it to move it, and tap it twice or use **Change** to change it."),
            ManualBlock(ManualKind.Heading, "The sheet"),
            ManualBlock(ManualKind.Para, "**Sheet** sets:"),
            ManualBlock(ManualKind.Bullet, "the paper: A4, A3, A2, Letter or Tabloid, and landscape or portrait;"),
            ManualBlock(ManualKind.Bullet, "the scale: from 10:1 to 1:100;"),
            ManualBlock(ManualKind.Bullet, "**Third angle** (the top view above the front, as in North America) or **First angle** (the top view below);"),
            ManualBlock(ManualKind.Bullet, "the title and who drew it, for the title block. The date is filled in."),
            ManualBlock(ManualKind.Para, "**Lay out the views again** puts the standard views back in their places, fitted to the sheet. It takes away the dimensions, since their views move."),
            ManualBlock(ManualKind.Heading, "Saving the drawing"),
            ManualBlock(ManualKind.Para, "The button at the top right saves the sheet:"),
            ManualBlock(ManualKind.Bullet, "**PDF** to print or send. It prints at its true size: at 1:1, a 40 mm part measures 40 mm on the paper."),
            ManualBlock(ManualKind.Bullet, "**DXF** for laser cutters and other drawing programs, with seen lines, hidden lines and notes on their own layers."),
            ManualBlock(ManualKind.Bullet, "**SVG** for the web or to edit."),
            ManualBlock(ManualKind.Para, "The drawing is saved with the design, and undo works on it the same as on the model."),
        )),
        ManualSection("Parameters and configurations", "Named sizes, and versions of a part.", listOf(
            ManualBlock(ManualKind.Heading, "Parameters"),
            ManualBlock(ManualKind.Para, "**Parameters**, under **Inspect**, is a table of named values. **Add a parameter** gives one a name and a value, which can itself use others, like `wall*2`. A name is letters, digits and `_`, starting with a letter."),
            ManualBlock(ManualKind.Para, "Any size in a sketch or a tool can then use the names. Change a parameter and everything that uses it changes, so a box can be made bigger by changing one number."),
            ManualBlock(ManualKind.Para, "**Save as CSV** saves the table as a CSV file with each parameter's name, expression and value, to keep or change in a spreadsheet. **Read CSV** reads one back: parameters with the same name take its expression, and new names are added. A row with no expression takes its value. The first row can be a heading, and the cells can be split by commas or semicolons."),
            ManualBlock(ManualKind.Heading, "Configurations"),
            ManualBlock(ManualKind.Para, "A configuration keeps a set of parameter values and which steps are turned off, under a name. Use them for versions of a part, like a small and a large size, or with and without a lid."),
            ManualBlock(ManualKind.Para, "At the top of the Parameters table, **Save as a configuration** keeps the current values and switched off steps under a name. Tap a configuration's chip to switch to it. With one chosen, **Update** saves your changes back to it, **Save as new** keeps them as another one, and the delete button beside them takes it away."),
        )),
        ManualSection("Files", "Saving, opening, exporting, and keeping designs in sync.", listOf(
            ManualBlock(ManualKind.Heading, "Saving"),
            ManualBlock(ManualKind.Para, "The design you're working on is saved as you go: every 30 seconds while there are changes, and whenever the app goes to the background or closes. **Continue** on the start screen picks it up again."),
            ManualBlock(ManualKind.Para, "To keep a design under a name, use **Save as…** in the menu under the parrot. After that **Save** writes to the same file. With a projects folder, designs are saved there without asking (see below)."),
            ManualBlock(ManualKind.Para, "ParrotMetric's own files end in `.pmet` and keep the whole history, so everything can still be changed when you open one again."),
            ManualBlock(ManualKind.Para, "In a browser, **Save as…** downloads the file."),
            ManualBlock(ManualKind.Heading, "Opening"),
            ManualBlock(ManualKind.Para, "**Open…** takes:"),
            ManualBlock(ManualKind.Bullet, "a `.pmet` design, which replaces the one that's open"),
            ManualBlock(ManualKind.Bullet, "an STL, 3MF or OBJ mesh, which is added as a mesh body (see Meshes)"),
            ManualBlock(ManualKind.Bullet, "a STEP or IGES file, which comes in as solids you can keep working on, as one step with no history of its own"),
            ManualBlock(ManualKind.Bullet, "a PNG or JPEG picture, which goes on a plane as a canvas to trace"),
            ManualBlock(ManualKind.Para, "From the start screen, a mesh, a STEP file or a picture starts a new design."),
            ManualBlock(ManualKind.Heading, "Exporting"),
            ManualBlock(ManualKind.Para, "**Export…** in the menu saves the shown bodies for printing or for other programs:"),
            ManualBlock(ManualKind.Bullet, "**STL**, **3MF** and **OBJ** are meshes for slicers. 3MF keeps each body's colour. Choose **Fine**, **Medium** or **Coarse**, which is how closely the triangles follow curved faces."),
            ManualBlock(ManualKind.Bullet, "**STEP** and **IGES** keep the exact shapes, for other CAD programs."),
            ManualBlock(ManualKind.Para, "It exports **All shown bodies** together, or tap bodies or components in the list to export just those."),
            ManualBlock(ManualKind.Heading, "Sending to a slicer"),
            ManualBlock(ManualKind.Para, "The Export sheet can also hand the part straight to a slicer, as a 3MF that keeps each body and its colour."),
            ManualBlock(ManualKind.Bullet, "On a computer there's an **Open in** button for each slicer it finds: Bambu Studio, OrcaSlicer, PrusaSlicer and Cura. **Open with the default app** opens it in whatever opens 3MF files."),
            ManualBlock(ManualKind.Bullet, "On Android, **Share…** sends it through the share sheet, to Drive, an email or another app."),
            ManualBlock(ManualKind.Para, "ParrotMetric doesn't slice, so printing goes through your slicer as usual. For a Bambu printer, open it in Bambu Studio or OrcaSlicer and print from there."),
            ManualBlock(ManualKind.Heading, "Keeping designs in sync"),
            ManualBlock(ManualKind.Para, "In Settings, **Projects folder** lets you keep your designs in one place so they're the same on every device."),
            ManualBlock(ManualKind.Bullet, "**Choose folder…** picks a folder on the device. Use one that a sync app looks after, such as Nextcloud, Syncthing or Dropbox."),
            ManualBlock(ManualKind.Bullet, "**WebDAV server…** uses a folder on a WebDAV server, such as Nextcloud, directly. Enter the folder's address, your user name and password, and tap **Connect**."),
            ManualBlock(ManualKind.Para, "For Nextcloud, the address looks like `https://your.server/remote.php/dav/files/USERNAME/ParrotMetric/`. Make the folder first, and use an app password from Nextcloud's security settings."),
            ManualBlock(ManualKind.Para, "With a projects folder, the start screen lists the designs in it, newest first, and tapping one opens it. New designs are saved there as you work, named after the design."),
            ManualBlock(ManualKind.Para, "When you come back to the app, it loads a newer copy if another device has changed the design you have open, as long as you haven't changed it here too. If it was changed in both places, both are kept: yours is saved beside the other with the device's name added, like `Box (Pixel 5).pmet`."),
            ManualBlock(ManualKind.Para, "The browser version can only use a server that allows requests from other sites (CORS), which most don't unless set up for it."),
            ManualBlock(ManualKind.Para, "**Stop using** goes back to no projects folder. The designs stay where they are."),
        )),
        ManualSection("Mouse and keyboard", "Using ParrotMetric at a desk.", listOf(
            ManualBlock(ManualKind.Para, "Everything works by touch, but with a mouse and a keyboard most things are quicker."),
            ManualBlock(ManualKind.Heading, "The mouse"),
            ManualBlock(ManualKind.Bullet, "The middle button drags the view along, and Shift and the middle button turns it. Right drag turns it too, and Shift and a right drag drags it along, which is handy on a touchpad. Looking steeply down or up at the model, a turn started on the far half of the view goes the other way, so the side you grab follows the mouse."),
            ManualBlock(ManualKind.Bullet, "The wheel zooms towards the pointer. A double middle click fits everything in view."),
            ManualBlock(ManualKind.Bullet, "In a browser, a two-finger scroll on a touchpad drags the view along and a pinch zooms."),
            ManualBlock(ManualKind.Bullet, "A click picks one thing in place of what was picked, and Shift or Ctrl and a click adds to it or takes away."),
            ManualBlock(ManualKind.Bullet, "A double-click on an edge also picks the edges running on smoothly from it."),
            ManualBlock(ManualKind.Bullet, "Dragging on empty space picks what's in a box: to the right, what's wholly inside it; to the left, anything it touches."),
            ManualBlock(ManualKind.Bullet, "A right-click gives **Repeat** for the last tool, the tools that suit what's picked, **Hide**, **Fit the view** and **Clear selection**. On a history chip it gives the chip's menu."),
            ManualBlock(ManualKind.Heading, "Keys"),
            ManualBlock(ManualKind.Para, "Press **?** for the list of every key, **S** to find a tool by typing its name and **F1** for this manual. When a keyboard is attached, the buttons show their keys."),
            ManualBlock(ManualKind.Bullet, "Most tools have a letter: **E** extrude, **F** fillet, **H** hole, **P** pattern, **M** move, **I** measure and so on. Shift and the letter is often the tool next to it, like **Shift+E** revolve and **Shift+F** chamfer. **N** sketches on what's picked."),
            ManualBlock(ManualKind.Bullet, "**Ctrl+N**, **Ctrl+O**, **Ctrl+S**, **Ctrl+Shift+S** and **Ctrl+E** are new, open, save, save as and export. **Ctrl+Z** undoes, and **Ctrl+Shift+Z** or **Ctrl+Y** redoes. Alt works in place of Ctrl, for keyboards without one."),
            ManualBlock(ManualKind.Bullet, "**1** to **6** look from the front, back, top, bottom, left and right, and **0** goes back to the home view. **V** fits everything in view."),
            ManualBlock(ManualKind.Bullet, "**Esc** or **Backspace** backs out of a tool or a sketch tool."),
            ManualBlock(ManualKind.Bullet, "In a tool's panel, typing a number, a minus sign, or the name of a parameter, goes into its first size. **Tab** moves to the next one, and **Enter** is **Done**."),
            ManualBlock(ManualKind.Heading, "In a sketch"),
            ManualBlock(ManualKind.Bullet, "**L** line, **R** rectangle, **C** circle, **A** arc, **G** polygon, **Shift+L** slot, **Shift+S** spline, **Shift+C** ellipse, **Shift+P** point and **Shift+T** text. Pressing a tool's letter again switches between its styles."),
            ManualBlock(ManualKind.Bullet, "**D** dimension, **T** trim, **E** extend, **B** break, **O** offset, **F** round corner, **Shift+F** cut corner, **M** move, **Shift+M** mirror and **X** construction. **H** and **V** make what's picked horizontal or vertical. **Delete** takes away what's picked."),
            ManualBlock(ManualKind.Bullet, "While drawing, type a size and it's used for the next point. **Tab** moves between sizes, such as the width and height of a rectangle, and **Enter** or a click places the shape that way."),
            ManualBlock(ManualKind.Bullet, "While a size, text or pattern sheet is open, typing goes into it, not to the tools."),
            ManualBlock(ManualKind.Bullet, "**Ctrl+Enter** finishes the sketch."),
            ManualBlock(ManualKind.Bullet, "With **Select**, dragging on empty space picks what's in a box, the same as on the model: to the right what's wholly inside, to the left anything it touches. Hold **Shift** to add to what's picked. Double-click a curve to pick its whole outline."),
            ManualBlock(ManualKind.Heading, "Sculpting"),
            ManualBlock(ManualKind.Bullet, "**D** draw, **C** clay, **Shift+C** crease, **S** smooth, **F** flatten, **I** inflate, **P** pinch, **G** grab, **Shift+G** pull, **L** layer and **M** mask."),
            ManualBlock(ManualKind.Bullet, "**[** and **]** make the brush smaller and bigger, and **X** inverts it."),
            ManualBlock(ManualKind.Bullet, "Shift while stroking smooths, and Ctrl does the opposite of the brush."),
            ManualBlock(ManualKind.Bullet, "**Shift+D** makes it finer all over, and **Shift+W** shows its triangles."),
            ManualBlock(ManualKind.Bullet, "**Ctrl+Z** undoes a stroke, and **Ctrl+Enter** is **Done**."),
        )),
        ManualSection("Settings", "The layout, how much detail the view shows, and the projects folder.", listOf(
            ManualBlock(ManualKind.Para, "Settings is on the start screen and in the menu under the parrot."),
            ManualBlock(ManualKind.Bullet, "**Layout** is **Automatic**, picked by the window's size, or always **Phone** or always **Large screen**."),
            ManualBlock(ManualKind.Bullet, "**Display detail** is how finely curved faces are drawn. **Automatic** picks it from a quick speed test the first time the app runs, and shows what it picked. Lower detail keeps the view smooth on older devices. It doesn't change what you export."),
            ManualBlock(ManualKind.Bullet, "**Projects folder** is a folder or a WebDAV server to keep your designs in. See Files."),
        )),
    )
}
